import type { AchievementDefinition } from "@domains/games/types/achievement";

export const ACHIEVEMENTS_CATALOG: AchievementDefinition[] = [
  {
    key: "first_game",
    title: "Primer paso",
    description: "Completa tu primer juego.",
    rarity: "common",
    target: 1,
    metric: "games",
    placeholderIcon: "/icons/achievements/first-game.svg",
  },
  {
    key: "games_5",
    title: "Coleccion en marcha",
    description: "Completa 5 juegos.",
    rarity: "common",
    target: 5,
    metric: "games",
    placeholderIcon: "/icons/achievements/games-5.svg",
  },
  {
    key: "games_10",
    title: "Constancia total",
    description: "Completa 10 juegos.",
    rarity: "rare",
    target: 10,
    metric: "games",
    placeholderIcon: "/icons/achievements/games-10.svg",
  },
  {
    key: "games_25",
    title: "Archivo historico",
    description: "Completa 25 juegos.",
    rarity: "epic",
    target: 25,
    metric: "games",
    placeholderIcon: "/icons/achievements/games-25.svg",
  },
  {
    key: "hours_50",
    title: "Maraton inicial",
    description: "Registra 50 horas jugadas.",
    rarity: "common",
    target: 50,
    metric: "hours",
    placeholderIcon: "/icons/achievements/hours-50.svg",
  },
  {
    key: "hours_100",
    title: "Ritmo experto",
    description: "Registra 100 horas jugadas.",
    rarity: "rare",
    target: 100,
    metric: "hours",
    placeholderIcon: "/icons/achievements/hours-100.svg",
  },
  {
    key: "hours_250",
    title: "Leyenda de tiempo",
    description: "Registra 250 horas jugadas.",
    rarity: "epic",
    target: 250,
    metric: "hours",
    placeholderIcon: "/icons/achievements/hours-250.svg",
  },
  {
    key: "score_90",
    title: "Critico interno",
    description: "Registra al menos un juego con puntuacion de 90 o mas.",
    rarity: "rare",
    target: 90,
    metric: "score",
    placeholderIcon: "/icons/achievements/score-90.svg",
  },
  {
    key: "platforms_3",
    title: "Multiplataforma",
    description: "Completa juegos en 3 plataformas diferentes.",
    rarity: "rare",
    target: 3,
    metric: "platforms",
    placeholderIcon: "/icons/achievements/platforms-3.svg",
  },
];
